### ISSUE TITLE
Permission denied in iOS

### ISSUE THREAD

**Issue by hamzamon** [derTuca/flutter_sim_country_code#3]
Hello, thank you for creating flutter_sim_country_code plugin its working in android like a charm but having faced an issue with iOS.
Description:  [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x283069820, domain=1, instance=1>

How to resolve this issue.
Regards.

**Comment by 00AhmedMokhtar00** [comment]
I'm having the same issue here

**Comment by AlaaEldeenYsr** [comment]
Any updates here ?

**Comment by balajiks-dev** [comment]
Any updates here?

**Comment by derTuca** [comment]
Sorry for the delay! I don't have a physical device to test, but I've migrated the code to use the newer API on iOS 12 and up, so it shouldn't pop up anymore. Please reopen the issue if it does.
