### ISSUE TITLE
Last vesion not released?

### ISSUE THREAD

**Issue by dragosholban** [derTuca/flutter_sim_country_code#9]
Because FameUp depends on flutter_sim_country_code ^0.1.2 which doesn't match any versions, version solving failed.

**Comment by bitosaez** [comment]
@derTuca when the newer version will be releasing to pub.dev? Because the fix for the issue with iOS Unhandled Exception: PlatformException was made in 0.1.2.

**Comment by derTuca** [comment]
I have released the version, sorry for the delay.
